version: '3.5'

services:
  backoffice:
    container_name: fixtab_backoffice_local
    image: fixtab_backoffice_local
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./.env
    tty: true
    volumes:
      - ./:/app
