#!/bin/sh

DEPLOYMENT_PATH=./k8s/deployment.yaml

# Replace ENV
sed -i "s|<NODE_ENV>|$NODE_ENV|g" $DEPLOYMENT_PATH
sed -i "s|<SKIP_PREFLIGHT_CHECK>|$SKIP_PREFLIGHT_CHECK|g" $DEPLOYMENT_PATH
sed -i "s|<GENERATE_SOURCEMAP>|$GENERATE_SOURCEMAP|g" $DEPLOYMENT_PATH
sed -i "s|<REACT_APP_API_URL>|$REACT_APP_API_URL|g" $DEPLOYMENT_PATH
sed -i "s|<REACT_APP_KEYCLOAK_URL>|$REACT_APP_KEYCLOAK_URL|g" $DEPLOYMENT_PATH
sed -i "s|<REACT_APP_KEYCLOAK_REALM>|$REACT_APP_KEYCLOAK_REALM|g" $DEPLOYMENT_PATH
sed -i "s|<REACT_APP_KEYCLOAK_CLIENT_ID>|$REACT_APP_KEYCLOAK_CLIENT_ID|g" $DEPLOYMENT_PATH
sed -i "s|<REACT_APP_KEYCLOAK_REDIRECT_URL>|$REACT_APP_KEYCLOAK_REDIRECT_URL|g" $DEPLOYMENT_PATH
sed -i "s|<REACT_APP_SENTRY_DSN>|$REACT_APP_SENTRY_DSN|g" $DEPLOYMENT_PATH
sed -i "s|<REACT_APP_SENTRY_RELEASE>|$REACT_APP_SENTRY_RELEASE|g" $DEPLOYMENT_PATH
sed -i "s|<REACT_APP_TRACES_SAMPLE_RATE>|$REACT_APP_TRACES_SAMPLE_RATE|g" $DEPLOYMENT_PATH

# Replace k8s environment
sed -i "s|<APP_NAME>|$APP_NAME|g" $DEPLOYMENT_PATH
sed -i "s|<IMAGE>|$IMAGE|g" $DEPLOYMENT_PATH
sed -i "s|<IMAGE_TAG>|$IMAGE_TAG|g" $DEPLOYMENT_PATH
sed -i "s|<NAMESPACE>|$K8S_NAMESPACE|g" $DEPLOYMENT_PATH
sed -i "s|<REPLICAS>|$K8S_REPLICAS|g" $DEPLOYMENT_PATH
sed -i "s|<CPU_LIMIT>|$K8S_CPU_LIMIT|g" $DEPLOYMENT_PATH
sed -i "s|<MEMORY_LIMIT>|$K8S_MEMORY_LIMIT|g" $DEPLOYMENT_PATH
sed -i "s|<CPU_REQUEST>|$K8S_CPU_REQUEST|g" $DEPLOYMENT_PATH
sed -i "s|<MEMORY_REQUEST>|$K8S_MEMORY_REQUEST|g" $DEPLOYMENT_PATH
sed -i "s|<DOMAIN_NAME>|$K8S_DOMAIN_NAME|g" $DEPLOYMENT_PATH

# Apple k8s
cat $DEPLOYMENT_PATH
kubectl apply -f $DEPLOYMENT_PATH

# Restart pod
kubectl rollout restart deployment/$APP_NAME --namespace=$K8S_NAMESPACE
