export const deleteAllGlobalPlayers = jest.fn()
export const deletePlayer = jest.fn()
export const deleteRoom = jest.fn()
export const deleteRoomPlayer = jest.fn()
export const setPlayer = jest.fn()
export const setRoom = jest.fn()
export const setRoomPlayer = jest.fn()
